### ISSUE TITLE
Is there any way to download snapshot SELPA certified report?

### ISSUE THREAD

**Issue by ruibianexcom** [yo-my-bard/calpads#18]
I can only download the ODS report. But I cannot download snapshot report. 
When I use dry run, it cannot return anything.  Please help me about this issue, Thank you so much! @yusuphisms

**Comment by yusuphisms** [comment]
Hello there! Thanks for using the library and for posting an issue!

**Without posting sensitive information**, can you please post a code snippet of how you are using the library? From your comment, I think you should set `dry_run=false` if you want it to actually download the report.

Thanks!

**Comment by ruibianexcom** [comment]
@yusuphisms Thank you.
Can you check why the 'Status' is empty tuple like this ` 'Status': ()`  when I use dry-run? 
And when I put 'Status': 'SELPA Approved' in form_input, the error shows 
```
 formname = self.complete_parse[paramname][1][1][0][1]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: tuple index out of range

```

**Comment by yusuphisms** [comment]
@ruibianexcom thanks for the error! Can you please share the code that you wrote to get this error?

**Comment by yusuphisms** [comment]
Can you also share the dry run output? Feel free to replace any sensitive info in the output.

Disclaimer: I don't have direct access to Calpads these days 😀 so I'm mostly going off of what I remember.

What you have shared suggests that there is no report available with any status. So it might be better to leave that input out. But please do share the additional info and I'd be happy to take a look.

**Comment by ruibianexcom** [comment]
@yusuphisms, Thank you. I find there is some issue about LEA. If I choose different LEA, the status is different. I think It is hard to download using API. I manage to download using selenium, so I think it is the way I download the records in the future. Thank you.

**Comment by yusuphisms** [comment]
Good to hear that Selenium works! And thanks for the valuable feedback.
